<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerG5pmfop\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerG5pmfop/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerG5pmfop.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerG5pmfop\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerG5pmfop\appProdProjectContainer([
    'container.build_hash' => 'G5pmfop',
    'container.build_id' => '879230f5',
    'container.build_time' => 1554203054,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerG5pmfop');
